# Generated by Django 5.1.4 on 2024-12-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_qualite', models.CharField()),
                ('prix_seance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_siege', models.CharField()),
                ('Num_rangee', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Synopsis', models.CharField(max_length=200)),
                ('Affiche', models.ImageField(upload_to=' ')),
                ('Date_ajout', models.DateField()),
                ('Age_min', models.IntegerField()),
                ('Note', models.FloatField()),
                ('ID_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_salle', models.CharField(verbose_name=2)),
                ('nb_places', models.IntegerField()),
                ('Places_PMR', models.IntegerField()),
                ('ID_qualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.qualite')),
            ],
        ),
        migrations.CreateModel(
            name='seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heure_debut', models.TimeField()),
                ('Heure_fin', models.TimeField()),
                ('Id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.film')),
                ('Id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.salle')),
            ],
        ),
    ]
