# Generated by Django 5.1.7 on 2025-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
