# Generated by Django 5.1.7 on 2025-03-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0002_film_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_ajout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
