# Generated by Django 4.2.17 on 2024-12-24 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0002_user_alter_film_synopsis_alter_genre_genre_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0.0)),
                ('commentaire', models.TextField(default='Pas de commentaire')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_billet', models.CharField(default='000000', max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='Anonyme', max_length=100)),
                ('objet_demande', models.CharField(default='Objet inconnu', max_length=100)),
                ('description', models.TextField(default='Pas de description')),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(default='Type inconnu', max_length=100)),
                ('type_materiel', models.CharField(default='Matériel inconnu', max_length=100)),
                ('description', models.TextField(default='Description non disponible')),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='Ouvert', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Action inconnue', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Aucune notification', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('nombre_places', models.IntegerField(default=1)),
                ('prix_total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSiege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='Aucune description')),
            ],
        ),
        migrations.CreateModel(
            name='StatutReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(default='Nom inconnu', max_length=50)),
                ('prenom', models.CharField(default='Prénom inconnu', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=100)),
                ('pays', models.CharField(default='France', max_length=50)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinephoria_webapp.role')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='ID_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='ID_qualite',
            new_name='qualite',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='Id_film',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='Id_salle',
            new_name='salle',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='CP',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='ID_seance',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='Pays',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='Ville',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Affiche',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Age_min',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Date_ajout',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Synopsis',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Titre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='qualite',
            name='Type_qualite',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='Num_salle',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='Places_PMR',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='nb_places',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='Heure_debut',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='Heure_fin',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='Num_rangee',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='Num_siege',
        ),
        migrations.AddField(
            model_name='cinema',
            name='horaire_fermeture',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='horaire_ouverture',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seances',
            field=models.ManyToManyField(to='cinephoria_webapp.seance'),
        ),
        migrations.AddField(
            model_name='film',
            name='age_minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='film',
            name='label_coup_de_coeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualite',
            name='logo_qualite',
            field=models.ImageField(default='default/logo.png', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='salle',
            name='nombre_places',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='salle',
            name='numero_salle',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='siege',
            name='libre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siege',
            name='numero_siege',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AddField(
            model_name='siege',
            name='place_pmr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siege',
            name='rangee',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='siege',
            name='salle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualite',
            name='prix_seance',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='reservationsiege',
            name='siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.siege'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='incident',
            name='siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.siege'),
        ),
        migrations.AddField(
            model_name='incident',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.cinema'),
        ),
        migrations.AddField(
            model_name='contact',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='billet',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.reservation'),
        ),
        migrations.AddField(
            model_name='avis',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.film'),
        ),
        migrations.AddField(
            model_name='avis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='adresse',
            field=models.TextField(default='1 place des étoiles'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='cp',
            field=models.CharField(default='75000', max_length=10),
        ),
        migrations.AddField(
            model_name='cinema',
            name='nom',
            field=models.CharField(default='Cinéma inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='cinema',
            name='pays',
            field=models.CharField(default='France', max_length=50),
        ),
        migrations.AddField(
            model_name='cinema',
            name='telephone',
            field=models.CharField(default='01 23 45 67 89', max_length=20),
        ),
        migrations.AddField(
            model_name='cinema',
            name='ville',
            field=models.CharField(default='Paris', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='affiche',
            field=models.ImageField(default='default/affiche.jpg', upload_to='films/'),
        ),
        migrations.AddField(
            model_name='film',
            name='date_ajout',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='film',
            name='dernier_modificateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='cinephoria_webapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='film',
            name='note',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(default='Synopsis indisponible'),
        ),
        migrations.AddField(
            model_name='film',
            name='titre',
            field=models.CharField(default='Titre inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='qualite',
            name='type_qualite',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='salle',
            name='places_pmr',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(default='20:30'),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(default='22:00'),
        ),
    ]
