# Generated by Django 5.1.7 on 2025-04-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0003_alter_film_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='seances',
        ),
        migrations.AddField(
            model_name='salle',
            name='Cinema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='cinephoria_webapp.cinema'),
        ),
    ]
