# Generated by Django 5.1.7 on 2025-04-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0004_remove_cinema_seances_salle_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='Cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='cinephoria_webapp.cinema'),
        ),
    ]
