# Generated by Django 5.1.7 on 2025-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0005_alter_salle_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(default='Paris', max_length=50),
        ),
    ]
