# Generated by Django 5.1.7 on 2025-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0006_utilisateur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(related_name='films', to='cinephoria_webapp.cinema'),
        ),
    ]
