# Generated by Django 5.1.7 on 2025-04-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0007_film_cinemas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salle',
            old_name='Cinema',
            new_name='cinema',
        ),
    ]
