# Generated by Django 5.1.7 on 2025-04-17 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0008_rename_cinema_salle_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
