# Generated by Django 5.1.7 on 2025-04-18 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0009_seance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='date',
        ),
        migrations.AlterField(
            model_name='film',
            name='date_ajout',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
