# Generated by Django 5.1.7 on 2025-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0010_remove_seance_date_alter_film_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_ajout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
