# Generated by Django 5.1.7 on 2025-04-18 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0011_alter_film_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
