# Generated by Django 5.1.7 on 2025-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0012_seance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourDeSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date',
        ),
        migrations.AddField(
            model_name='seance',
            name='jours',
            field=models.ManyToManyField(to='cinephoria_webapp.jourdesemaine'),
        ),
    ]
