# Generated by Django 5.1.7 on 2025-04-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0013_jourdesemaine_remove_seance_date_seance_jours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='jours',
        ),
        migrations.AddField(
            model_name='seance',
            name='jour_semaine',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=2),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='JourDeSemaine',
        ),
    ]
