# Generated by Django 5.1.7 on 2025-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0014_remove_seance_jours_seance_jour_semaine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='jour_semaine',
        ),
        migrations.AddField(
            model_name='film',
            name='duree',
            field=models.PositiveIntegerField(default=90, help_text='Durée en minutes'),
        ),
        migrations.AddField(
            model_name='seance',
            name='jours_diffusion',
            field=models.JSONField(default=list, help_text='Liste des jours (ex: [0, 2, 4])'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
