# Generated by Django 5.1.7 on 2025-05-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0016_alter_film_affiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinephoria_webapp.salle'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='siege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinephoria_webapp.siege'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_materiel',
            field=models.CharField(choices=[('siège', 'Siège'), ('écran', 'Écran'), ('porte', 'Porte'), ('moquette', 'Moquette'), ('son', 'Son'), ('éclairage', 'Éclairage'), ('autre', 'Autre')], default='autre', max_length=100),
        ),
    ]
