# Generated by Django 5.1.7 on 2025-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0017_incident_salle_alter_incident_siege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='validé',
            field=models.BooleanField(default=False),
        ),
    ]
