# Generated by Django 5.1.7 on 2025-05-21 08:37

import cinephoria_webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0018_avis_validé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='numero_billet',
            field=models.CharField(default=cinephoria_webapp.models.Billet.generate_unique_billet_number, max_length=20, unique=True),
        ),
    ]
