# Generated by Django 5.1.7 on 2025-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0019_alter_billet_numero_billet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='validé',
            new_name='valide',
        ),
    ]
