# Generated by Django 5.1.7 on 2025-05-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0020_rename_validé_avis_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
    ]
