# Generated by Django 5.1.7 on 2025-05-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0021_utilisateur_doit_changer_mdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='doit_changer_mdp',
        ),
    ]
