# Generated by Django 5.1.7 on 2025-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0024_alter_contact_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='films/'),
        ),
    ]
