# Generated by Django 5.1.7 on 2025-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0025_alter_film_affiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='affiche_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
