# Generated by Django 5.1.7 on 2025-05-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0026_film_affiche_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billet', to='cinephoria_webapp.reservation'),
        ),
    ]
