# Generated by Django 5.1.7 on 2025-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephoria_webapp', '0027_alter_billet_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_projection',
            field=models.DateField(blank=True, null=True),
        ),
    ]
