name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cinephoria_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: False
      SECRET_KEY: dummysecretkeyforci
      POSTGRES_DB: cinephoria_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Heroku CLI and authenticate
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "machine git.heroku.com" >> ~/.netrc
          echo " login ${HEROKU_EMAIL}" >> ~/.netrc
          echo " password ${HEROKU_API_KEY}" >> ~/.netrc
          echo "machine api.heroku.com" >> ~/.netrc
          echo " login ${HEROKU_EMAIL}" >> ~/.netrc
          echo " password ${HEROKU_API_KEY}" >> ~/.netrc
          chmod 600 ~/.netrc
        env:
          DJANGO_SETTINGS_MODULE: settings.prod
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Add Heroku remote
        run: git remote add heroku https://git.heroku.com/cinephoria-cinemas.git

      - name: Unshallow the repository
        run: git fetch --unshallow

      - name: Push to Heroku
        run: git push heroku main --force

      - name: Run migrations on Heroku
        run: heroku run python manage.py migrate --app cinephoria-cinemas
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Run collectstatic on Heroku
        run: heroku run --app cinephoria-cinemas -- python manage.py collectstatic --noinput
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
